language: perl
perl:
  - "5.18"
# - "5.16"
  - "5.14"
# - "5.12"
  - "5.10"
# 5.10 is the oldest perl on Travis-CI

#branches:
#  only:
#    - releases

# Travis: http://blogs.perl.org/users/alex_balhatchet/2013/04/travis-ci-perl.html

before_install:
   # Prevent "Please tell me who you are" errors for certain DZIL configs
   - git config --global user.name "TravisCI"

install:

   # Deal with all of the DZIL dependencies, quickly and quietly
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - cpanm --quiet --notest --skip-satisfied Pod::Weaver::Section::Contributors

   - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied

   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1

   - dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose

# using Socket6 instead, no need to force this upgrade
#  - cpanm --quiet --notest --skip-satisfied 'Socket~2'

script:

   - dzil smoke --release --author
